# the high level policy
policy:
  approval:
    - or:
      - the devtools team has approved
      - only staging files have changed
  disapproval:
    requires:
      organizations:
        - "IntelliTect-Enterprise"

# the list of rules
approval_rules:
  - name: the devtools team has approved
    requires:
      count: 1
      teams:
        - "IntelliTect-Enterprise/Solve2017"
  - name: only staging files have changed
    if:
      only_changed_files:
        paths:
          - "**/.*"
    requires:
      count: 0
